### ISSUE TITLE
Cannot map parametric function

### ISSUE THREAD

**Issue by grebe** [google/xls#1412] opened 2024-05-16 23:45 UTC
Mapping a parametric function doesn't work, e.g.

```
fn f<N:u32>(x: u32) -> u32 { N + x }
fn main() { map(u32[4]:[0, 1, 2, 3], f<u32:4>) }
```

**Comment by hzeller** [comment] 2024-06-17 17:07
Also duplicate of https://github.com/google/xls/issues/1063

**Comment by mikex-oss** [comment] 2024-06-17 22:59
I think #1063 is a specific case of this bug for which there can be no available workaround. I.e. you can't simply wrap the parametric instantiation because it depends on parent parameters.

This more generalized issue can be worked around as indicated in https://github.com/google/xls/issues/1063#issuecomment-1633497494.

Not sure what this means for bug management...

**Comment by proppy** [comment] 2024-06-17 23:00
Let's keep this open then, and #1063 as "related" then.

Sorry for the nosie :)

**Closed** 2024-10-21 19:20 UTC
Labels: bug, dslx, 🧦 sox
