### ISSUE TITLE
The DSLX parser chokes on module constants in bit slice statements.

### ISSUE THREAD

**Issue by rmlarsen** [google/xls#1783] opened 2024-12-10 21:28 UTC
**Describe the bug**
The DSLX parser chokes on module constants in bit slice statements.

**To Reproduce**

```
import mymodule;
let foo = u32:42;
let bar = foo[mymodule::BEGIN : mymodule::END];
```

**Expected behavior**
I would expect the slice statement to extract bits from `foo` in the open interval specified by constants `BEGIN` and `END` in `mymodule`.

**Comment by mikex-oss** [comment] 2024-12-10 21:36
Duplicate of https://github.com/google/xls/issues/1727

**Closed by mikex-oss** 2024-12-10 21:36 UTC
